/**
 * generated by Xtext 2.25.0
 */
package org.qwork.osolqiraa.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.qwork.osolqiraa.HarfQuran;
import org.qwork.osolqiraa.OsolqiraaPackage;

import org.qwork.qayahstart.AyahStart;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Harf Quran</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.osolqiraa.impl.HarfQuranImpl#getWord <em>Word</em>}</li>
 *   <li>{@link org.qwork.osolqiraa.impl.HarfQuranImpl#getAyah <em>Ayah</em>}</li>
 *   <li>{@link org.qwork.osolqiraa.impl.HarfQuranImpl#getMawdee <em>Mawdee</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HarfQuranImpl extends MinimalEObjectImpl.Container implements HarfQuran
{
  /**
   * The default value of the '{@link #getWord() <em>Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWord()
   * @generated
   * @ordered
   */
  protected static final String WORD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWord() <em>Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWord()
   * @generated
   * @ordered
   */
  protected String word = WORD_EDEFAULT;

  /**
   * The cached value of the '{@link #getAyah() <em>Ayah</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAyah()
   * @generated
   * @ordered
   */
  protected AyahStart ayah;

  /**
   * The default value of the '{@link #getMawdee() <em>Mawdee</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMawdee()
   * @generated
   * @ordered
   */
  protected static final String MAWDEE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMawdee() <em>Mawdee</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMawdee()
   * @generated
   * @ordered
   */
  protected String mawdee = MAWDEE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HarfQuranImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OsolqiraaPackage.Literals.HARF_QURAN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWord()
  {
    return word;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWord(String newWord)
  {
    String oldWord = word;
    word = newWord;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OsolqiraaPackage.HARF_QURAN__WORD, oldWord, word));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AyahStart getAyah()
  {
    if (ayah != null && ayah.eIsProxy())
    {
      InternalEObject oldAyah = (InternalEObject)ayah;
      ayah = (AyahStart)eResolveProxy(oldAyah);
      if (ayah != oldAyah)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, OsolqiraaPackage.HARF_QURAN__AYAH, oldAyah, ayah));
      }
    }
    return ayah;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AyahStart basicGetAyah()
  {
    return ayah;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAyah(AyahStart newAyah)
  {
    AyahStart oldAyah = ayah;
    ayah = newAyah;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OsolqiraaPackage.HARF_QURAN__AYAH, oldAyah, ayah));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMawdee()
  {
    return mawdee;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMawdee(String newMawdee)
  {
    String oldMawdee = mawdee;
    mawdee = newMawdee;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OsolqiraaPackage.HARF_QURAN__MAWDEE, oldMawdee, mawdee));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OsolqiraaPackage.HARF_QURAN__WORD:
        return getWord();
      case OsolqiraaPackage.HARF_QURAN__AYAH:
        if (resolve) return getAyah();
        return basicGetAyah();
      case OsolqiraaPackage.HARF_QURAN__MAWDEE:
        return getMawdee();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OsolqiraaPackage.HARF_QURAN__WORD:
        setWord((String)newValue);
        return;
      case OsolqiraaPackage.HARF_QURAN__AYAH:
        setAyah((AyahStart)newValue);
        return;
      case OsolqiraaPackage.HARF_QURAN__MAWDEE:
        setMawdee((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OsolqiraaPackage.HARF_QURAN__WORD:
        setWord(WORD_EDEFAULT);
        return;
      case OsolqiraaPackage.HARF_QURAN__AYAH:
        setAyah((AyahStart)null);
        return;
      case OsolqiraaPackage.HARF_QURAN__MAWDEE:
        setMawdee(MAWDEE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OsolqiraaPackage.HARF_QURAN__WORD:
        return WORD_EDEFAULT == null ? word != null : !WORD_EDEFAULT.equals(word);
      case OsolqiraaPackage.HARF_QURAN__AYAH:
        return ayah != null;
      case OsolqiraaPackage.HARF_QURAN__MAWDEE:
        return MAWDEE_EDEFAULT == null ? mawdee != null : !MAWDEE_EDEFAULT.equals(mawdee);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (word: ");
    result.append(word);
    result.append(", mawdee: ");
    result.append(mawdee);
    result.append(')');
    return result.toString();
  }

} //HarfQuranImpl
