/*
 * generated by Xtext 2.25.0
 */
package org.qwork.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.qwork.ide.contentassist.antlr.internal.InternalAbjadParser;
import org.qwork.services.AbjadGrammarAccess;

public class AbjadParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AbjadGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AbjadGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAbjadModelAccess().getAlternatives(), "rule__AbjadModel__Alternatives");
			builder.put(grammarAccess.getHarfAccess().getAlternatives_2(), "rule__Harf__Alternatives_2");
			builder.put(grammarAccess.getHarfAccess().getGroup(), "rule__Harf__Group__0");
			builder.put(grammarAccess.getHarfAccess().getGroup_2_0(), "rule__Harf__Group_2_0__0");
			builder.put(grammarAccess.getHarfAccess().getGroup_2_0_2(), "rule__Harf__Group_2_0_2__0");
			builder.put(grammarAccess.getHarfAccess().getGroup_2_1(), "rule__Harf__Group_2_1__0");
			builder.put(grammarAccess.getHarakahAccess().getGroup(), "rule__Harakah__Group__0");
			builder.put(grammarAccess.getAyahStartAccess().getGroup(), "rule__AyahStart__Group__0");
			builder.put(grammarAccess.getPhraseAccess().getGroup(), "rule__Phrase__Group__0");
			builder.put(grammarAccess.getPhraseAccess().getGroup_1(), "rule__Phrase__Group_1__0");
			builder.put(grammarAccess.getAbjadModelAccess().getHouroufAssignment_0(), "rule__AbjadModel__HouroufAssignment_0");
			builder.put(grammarAccess.getAbjadModelAccess().getHarakatAssignment_1(), "rule__AbjadModel__HarakatAssignment_1");
			builder.put(grammarAccess.getHarfAccess().getNameAssignment_1(), "rule__Harf__NameAssignment_1");
			builder.put(grammarAccess.getHarfAccess().getValuesAssignment_2_0_1(), "rule__Harf__ValuesAssignment_2_0_1");
			builder.put(grammarAccess.getHarfAccess().getValuesAssignment_2_0_2_1(), "rule__Harf__ValuesAssignment_2_0_2_1");
			builder.put(grammarAccess.getHarfAccess().getRefAssignment_2_1_1(), "rule__Harf__RefAssignment_2_1_1");
			builder.put(grammarAccess.getHarakahAccess().getNameAssignment_1(), "rule__Harakah__NameAssignment_1");
			builder.put(grammarAccess.getHarakahAccess().getValueAssignment_3(), "rule__Harakah__ValueAssignment_3");
			builder.put(grammarAccess.getAyahStartModelAccess().getAyatAssignment(), "rule__AyahStartModel__AyatAssignment");
			builder.put(grammarAccess.getAyahStartAccess().getSurahAssignment_1(), "rule__AyahStart__SurahAssignment_1");
			builder.put(grammarAccess.getAyahStartAccess().getAyahAssignment_3(), "rule__AyahStart__AyahAssignment_3");
			builder.put(grammarAccess.getAyahStartAccess().getNameAssignment_4(), "rule__AyahStart__NameAssignment_4");
			builder.put(grammarAccess.getModelAccess().getPhrasesAssignment(), "rule__Model__PhrasesAssignment");
			builder.put(grammarAccess.getPhraseAccess().getWordsAssignment_0(), "rule__Phrase__WordsAssignment_0");
			builder.put(grammarAccess.getPhraseAccess().getWordsAssignment_1_1(), "rule__Phrase__WordsAssignment_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AbjadGrammarAccess grammarAccess;

	@Override
	protected InternalAbjadParser createParser() {
		InternalAbjadParser result = new InternalAbjadParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AbjadGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AbjadGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
