/*
 * generated by Xtext 2.25.0
 */
package org.qwork.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.qwork.ide.contentassist.antlr.internal.InternalArabicParser;
import org.qwork.services.ArabicGrammarAccess;

public class ArabicParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ArabicGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ArabicGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPhraseAccess().getGroup(), "rule__Phrase__Group__0");
			builder.put(grammarAccess.getPhraseAccess().getGroup_1(), "rule__Phrase__Group_1__0");
			builder.put(grammarAccess.getModelAccess().getPhrasesAssignment(), "rule__Model__PhrasesAssignment");
			builder.put(grammarAccess.getPhraseAccess().getWordsAssignment_0(), "rule__Phrase__WordsAssignment_0");
			builder.put(grammarAccess.getPhraseAccess().getWordsAssignment_1_1(), "rule__Phrase__WordsAssignment_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ArabicGrammarAccess grammarAccess;

	@Override
	protected InternalArabicParser createParser() {
		InternalArabicParser result = new InternalArabicParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ArabicGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArabicGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
