/*
 * generated by Xtext 2.25.0
 */
package org.qwork.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.qwork.ide.contentassist.antlr.internal.InternalQiraaParser;
import org.qwork.services.QiraaGrammarAccess;

public class QiraaParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(QiraaGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, QiraaGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getQiraaModelAccess().getAlternatives(), "rule__QiraaModel__Alternatives");
			builder.put(grammarAccess.getHarfAccess().getAlternatives_2(), "rule__Harf__Alternatives_2");
			builder.put(grammarAccess.getHarfAccess().getGroup(), "rule__Harf__Group__0");
			builder.put(grammarAccess.getHarfAccess().getGroup_2_0(), "rule__Harf__Group_2_0__0");
			builder.put(grammarAccess.getHarfAccess().getGroup_2_0_2(), "rule__Harf__Group_2_0_2__0");
			builder.put(grammarAccess.getHarfAccess().getGroup_2_1(), "rule__Harf__Group_2_1__0");
			builder.put(grammarAccess.getHarakahAccess().getGroup(), "rule__Harakah__Group__0");
			builder.put(grammarAccess.getQareeAccess().getGroup(), "rule__Qaree__Group__0");
			builder.put(grammarAccess.getRaweeAccess().getGroup(), "rule__Rawee__Group__0");
			builder.put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
			builder.put(grammarAccess.getPersonAccess().getGroup_1(), "rule__Person__Group_1__0");
			builder.put(grammarAccess.getPersonAccess().getGroup_2(), "rule__Person__Group_2__0");
			builder.put(grammarAccess.getPersonAccess().getGroup_3(), "rule__Person__Group_3__0");
			builder.put(grammarAccess.getTareekAccess().getGroup(), "rule__Tareek__Group__0");
			builder.put(grammarAccess.getTareekAccess().getGroup_2(), "rule__Tareek__Group_2__0");
			builder.put(grammarAccess.getPhraseAccess().getGroup(), "rule__Phrase__Group__0");
			builder.put(grammarAccess.getPhraseAccess().getGroup_1(), "rule__Phrase__Group_1__0");
			builder.put(grammarAccess.getQiraaModelAccess().getHouroufAssignment_0(), "rule__QiraaModel__HouroufAssignment_0");
			builder.put(grammarAccess.getQiraaModelAccess().getQoraaAssignment_1(), "rule__QiraaModel__QoraaAssignment_1");
			builder.put(grammarAccess.getQiraaModelAccess().getTorokAssignment_2(), "rule__QiraaModel__TorokAssignment_2");
			builder.put(grammarAccess.getQiraaModelAccess().getHarakatAssignment_3(), "rule__QiraaModel__HarakatAssignment_3");
			builder.put(grammarAccess.getQiraaModelAccess().getRowatAssignment_4(), "rule__QiraaModel__RowatAssignment_4");
			builder.put(grammarAccess.getHarfAccess().getNameAssignment_1(), "rule__Harf__NameAssignment_1");
			builder.put(grammarAccess.getHarfAccess().getValuesAssignment_2_0_1(), "rule__Harf__ValuesAssignment_2_0_1");
			builder.put(grammarAccess.getHarfAccess().getValuesAssignment_2_0_2_1(), "rule__Harf__ValuesAssignment_2_0_2_1");
			builder.put(grammarAccess.getHarfAccess().getRefAssignment_2_1_1(), "rule__Harf__RefAssignment_2_1_1");
			builder.put(grammarAccess.getHarakahAccess().getNameAssignment_1(), "rule__Harakah__NameAssignment_1");
			builder.put(grammarAccess.getHarakahAccess().getValueAssignment_3(), "rule__Harakah__ValueAssignment_3");
			builder.put(grammarAccess.getRaweeAccess().getQareeAssignment_3(), "rule__Rawee__QareeAssignment_3");
			builder.put(grammarAccess.getPersonAccess().getNameAssignment_0(), "rule__Person__NameAssignment_0");
			builder.put(grammarAccess.getPersonAccess().getEsmAssignment_1_1(), "rule__Person__EsmAssignment_1_1");
			builder.put(grammarAccess.getPersonAccess().getLakabAssignment_2_1(), "rule__Person__LakabAssignment_2_1");
			builder.put(grammarAccess.getPersonAccess().getTowofiaAssignment_3_1(), "rule__Person__TowofiaAssignment_3_1");
			builder.put(grammarAccess.getTareekAccess().getNameAssignment_1(), "rule__Tareek__NameAssignment_1");
			builder.put(grammarAccess.getTareekAccess().getRefAssignment_2_1(), "rule__Tareek__RefAssignment_2_1");
			builder.put(grammarAccess.getModelAccess().getPhrasesAssignment(), "rule__Model__PhrasesAssignment");
			builder.put(grammarAccess.getPhraseAccess().getWordsAssignment_0(), "rule__Phrase__WordsAssignment_0");
			builder.put(grammarAccess.getPhraseAccess().getWordsAssignment_1_1(), "rule__Phrase__WordsAssignment_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private QiraaGrammarAccess grammarAccess;

	@Override
	protected InternalQiraaParser createParser() {
		InternalQiraaParser result = new InternalQiraaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public QiraaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QiraaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
