/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qayahstart.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.qwork.qayahstart.AyahStart;
import org.qwork.qayahstart.AyahStartModel;
import org.qwork.qayahstart.QayahstartFactory;
import org.qwork.qayahstart.QayahstartPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class QayahstartPackageImpl extends EPackageImpl implements QayahstartPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ayahStartModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ayahStartEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.qwork.qayahstart.QayahstartPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private QayahstartPackageImpl()
  {
    super(eNS_URI, QayahstartFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link QayahstartPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static QayahstartPackage init()
  {
    if (isInited) return (QayahstartPackage)EPackage.Registry.INSTANCE.getEPackage(QayahstartPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredQayahstartPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    QayahstartPackageImpl theQayahstartPackage = registeredQayahstartPackage instanceof QayahstartPackageImpl ? (QayahstartPackageImpl)registeredQayahstartPackage : new QayahstartPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theQayahstartPackage.createPackageContents();

    // Initialize created meta-data
    theQayahstartPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theQayahstartPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(QayahstartPackage.eNS_URI, theQayahstartPackage);
    return theQayahstartPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAyahStartModel()
  {
    return ayahStartModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAyahStartModel_Ayat()
  {
    return (EReference)ayahStartModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAyahStart()
  {
    return ayahStartEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAyahStart_Surah()
  {
    return (EAttribute)ayahStartEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAyahStart_Ayah()
  {
    return (EAttribute)ayahStartEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAyahStart_Name()
  {
    return (EAttribute)ayahStartEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QayahstartFactory getQayahstartFactory()
  {
    return (QayahstartFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    ayahStartModelEClass = createEClass(AYAH_START_MODEL);
    createEReference(ayahStartModelEClass, AYAH_START_MODEL__AYAT);

    ayahStartEClass = createEClass(AYAH_START);
    createEAttribute(ayahStartEClass, AYAH_START__SURAH);
    createEAttribute(ayahStartEClass, AYAH_START__AYAH);
    createEAttribute(ayahStartEClass, AYAH_START__NAME);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(ayahStartModelEClass, AyahStartModel.class, "AyahStartModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAyahStartModel_Ayat(), this.getAyahStart(), null, "ayat", null, 0, -1, AyahStartModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ayahStartEClass, AyahStart.class, "AyahStart", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAyahStart_Surah(), ecorePackage.getEInt(), "surah", null, 0, 1, AyahStart.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAyahStart_Ayah(), ecorePackage.getEInt(), "ayah", null, 0, 1, AyahStart.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAyahStart_Name(), ecorePackage.getEString(), "name", null, 0, 1, AyahStart.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //QayahstartPackageImpl
