/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Harf</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.qiraa.Harf#getName <em>Name</em>}</li>
 *   <li>{@link org.qwork.qiraa.Harf#getValues <em>Values</em>}</li>
 *   <li>{@link org.qwork.qiraa.Harf#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.qwork.qiraa.QiraaPackage#getHarf()
 * @model
 * @generated
 */
public interface Harf extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.qwork.qiraa.QiraaPackage#getHarf_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.qwork.qiraa.Harf#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see org.qwork.qiraa.QiraaPackage#getHarf_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Harf)
   * @see org.qwork.qiraa.QiraaPackage#getHarf_Ref()
   * @model
   * @generated
   */
  Harf getRef();

  /**
   * Sets the value of the '{@link org.qwork.qiraa.Harf#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Harf value);

} // Harf
