/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.qwork.qiraa.QiraaFactory
 * @model kind="package"
 * @generated
 */
public interface QiraaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "qiraa";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.qwork.org/Qiraa";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "qiraa";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QiraaPackage eINSTANCE = org.qwork.qiraa.impl.QiraaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.QiraaModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.QiraaModelImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getQiraaModel()
   * @generated
   */
  int QIRAA_MODEL = 0;

  /**
   * The feature id for the '<em><b>Marjee</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QIRAA_MODEL__MARJEE = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QIRAA_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.MarjehImpl <em>Marjeh</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.MarjehImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getMarjeh()
   * @generated
   */
  int MARJEH = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARJEH__NAME = 0;

  /**
   * The feature id for the '<em><b>Matn</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARJEH__MATN = 1;

  /**
   * The feature id for the '<em><b>Romoz</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARJEH__ROMOZ = 2;

  /**
   * The feature id for the '<em><b>Tafsil</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARJEH__TAFSIL = 3;

  /**
   * The number of structural features of the '<em>Marjeh</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARJEH_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.TafsilImpl <em>Tafsil</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.TafsilImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getTafsil()
   * @generated
   */
  int TAFSIL = 2;

  /**
   * The feature id for the '<em><b>Nass</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAFSIL__NASS = 0;

  /**
   * The feature id for the '<em><b>Kedah</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAFSIL__KEDAH = 1;

  /**
   * The number of structural features of the '<em>Tafsil</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAFSIL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.KaaedahImpl <em>Kaaedah</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.KaaedahImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getKaaedah()
   * @generated
   */
  int KAAEDAH = 3;

  /**
   * The feature id for the '<em><b>Refs</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KAAEDAH__REFS = 0;

  /**
   * The feature id for the '<em><b>Kayd</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KAAEDAH__KAYD = 1;

  /**
   * The feature id for the '<em><b>Harf</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KAAEDAH__HARF = 2;

  /**
   * The number of structural features of the '<em>Kaaedah</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KAAEDAH_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.QiraaModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.qwork.qiraa.QiraaModel
   * @generated
   */
  EClass getQiraaModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.QiraaModel#getMarjee <em>Marjee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Marjee</em>'.
   * @see org.qwork.qiraa.QiraaModel#getMarjee()
   * @see #getQiraaModel()
   * @generated
   */
  EReference getQiraaModel_Marjee();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Marjeh <em>Marjeh</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Marjeh</em>'.
   * @see org.qwork.qiraa.Marjeh
   * @generated
   */
  EClass getMarjeh();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Marjeh#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.qwork.qiraa.Marjeh#getName()
   * @see #getMarjeh()
   * @generated
   */
  EAttribute getMarjeh_Name();

  /**
   * Returns the meta object for the reference '{@link org.qwork.qiraa.Marjeh#getMatn <em>Matn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Matn</em>'.
   * @see org.qwork.qiraa.Marjeh#getMatn()
   * @see #getMarjeh()
   * @generated
   */
  EReference getMarjeh_Matn();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.Marjeh#getRomoz <em>Romoz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Romoz</em>'.
   * @see org.qwork.qiraa.Marjeh#getRomoz()
   * @see #getMarjeh()
   * @generated
   */
  EReference getMarjeh_Romoz();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.Marjeh#getTafsil <em>Tafsil</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tafsil</em>'.
   * @see org.qwork.qiraa.Marjeh#getTafsil()
   * @see #getMarjeh()
   * @generated
   */
  EReference getMarjeh_Tafsil();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Tafsil <em>Tafsil</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tafsil</em>'.
   * @see org.qwork.qiraa.Tafsil
   * @generated
   */
  EClass getTafsil();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Tafsil#getNass <em>Nass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nass</em>'.
   * @see org.qwork.qiraa.Tafsil#getNass()
   * @see #getTafsil()
   * @generated
   */
  EAttribute getTafsil_Nass();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.Tafsil#getKedah <em>Kedah</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Kedah</em>'.
   * @see org.qwork.qiraa.Tafsil#getKedah()
   * @see #getTafsil()
   * @generated
   */
  EReference getTafsil_Kedah();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Kaaedah <em>Kaaedah</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Kaaedah</em>'.
   * @see org.qwork.qiraa.Kaaedah
   * @generated
   */
  EClass getKaaedah();

  /**
   * Returns the meta object for the reference list '{@link org.qwork.qiraa.Kaaedah#getRefs <em>Refs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Refs</em>'.
   * @see org.qwork.qiraa.Kaaedah#getRefs()
   * @see #getKaaedah()
   * @generated
   */
  EReference getKaaedah_Refs();

  /**
   * Returns the meta object for the reference '{@link org.qwork.qiraa.Kaaedah#getKayd <em>Kayd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Kayd</em>'.
   * @see org.qwork.qiraa.Kaaedah#getKayd()
   * @see #getKaaedah()
   * @generated
   */
  EReference getKaaedah_Kayd();

  /**
   * Returns the meta object for the containment reference '{@link org.qwork.qiraa.Kaaedah#getHarf <em>Harf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Harf</em>'.
   * @see org.qwork.qiraa.Kaaedah#getHarf()
   * @see #getKaaedah()
   * @generated
   */
  EReference getKaaedah_Harf();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QiraaFactory getQiraaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.QiraaModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.QiraaModelImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getQiraaModel()
     * @generated
     */
    EClass QIRAA_MODEL = eINSTANCE.getQiraaModel();

    /**
     * The meta object literal for the '<em><b>Marjee</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QIRAA_MODEL__MARJEE = eINSTANCE.getQiraaModel_Marjee();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.MarjehImpl <em>Marjeh</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.MarjehImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getMarjeh()
     * @generated
     */
    EClass MARJEH = eINSTANCE.getMarjeh();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MARJEH__NAME = eINSTANCE.getMarjeh_Name();

    /**
     * The meta object literal for the '<em><b>Matn</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MARJEH__MATN = eINSTANCE.getMarjeh_Matn();

    /**
     * The meta object literal for the '<em><b>Romoz</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MARJEH__ROMOZ = eINSTANCE.getMarjeh_Romoz();

    /**
     * The meta object literal for the '<em><b>Tafsil</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MARJEH__TAFSIL = eINSTANCE.getMarjeh_Tafsil();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.TafsilImpl <em>Tafsil</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.TafsilImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getTafsil()
     * @generated
     */
    EClass TAFSIL = eINSTANCE.getTafsil();

    /**
     * The meta object literal for the '<em><b>Nass</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAFSIL__NASS = eINSTANCE.getTafsil_Nass();

    /**
     * The meta object literal for the '<em><b>Kedah</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAFSIL__KEDAH = eINSTANCE.getTafsil_Kedah();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.KaaedahImpl <em>Kaaedah</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.KaaedahImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getKaaedah()
     * @generated
     */
    EClass KAAEDAH = eINSTANCE.getKaaedah();

    /**
     * The meta object literal for the '<em><b>Refs</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KAAEDAH__REFS = eINSTANCE.getKaaedah_Refs();

    /**
     * The meta object literal for the '<em><b>Kayd</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KAAEDAH__KAYD = eINSTANCE.getKaaedah_Kayd();

    /**
     * The meta object literal for the '<em><b>Harf</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KAAEDAH__HARF = eINSTANCE.getKaaedah_Harf();

  }

} //QiraaPackage
