/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.qwork.qiraa.QiraaFactory
 * @model kind="package"
 * @generated
 */
public interface QiraaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "qiraa";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.qwork.org/Qiraa";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "qiraa";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QiraaPackage eINSTANCE = org.qwork.qiraa.impl.QiraaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.QiraaModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.QiraaModelImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getQiraaModel()
   * @generated
   */
  int QIRAA_MODEL = 0;

  /**
   * The feature id for the '<em><b>Hourouf</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QIRAA_MODEL__HOUROUF = 0;

  /**
   * The feature id for the '<em><b>Qoraa</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QIRAA_MODEL__QORAA = 1;

  /**
   * The feature id for the '<em><b>Torok</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QIRAA_MODEL__TOROK = 2;

  /**
   * The feature id for the '<em><b>Harakat</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QIRAA_MODEL__HARAKAT = 3;

  /**
   * The feature id for the '<em><b>Rowat</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QIRAA_MODEL__ROWAT = 4;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QIRAA_MODEL_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.HarfImpl <em>Harf</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.HarfImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getHarf()
   * @generated
   */
  int HARF = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARF__NAME = 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARF__VALUES = 1;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARF__REF = 2;

  /**
   * The number of structural features of the '<em>Harf</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.HarakahImpl <em>Harakah</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.HarakahImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getHarakah()
   * @generated
   */
  int HARAKAH = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARAKAH__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARAKAH__VALUE = 1;

  /**
   * The number of structural features of the '<em>Harakah</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARAKAH_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.PersonImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The feature id for the '<em><b>Esm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__ESM = 1;

  /**
   * The feature id for the '<em><b>Lakab</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__LAKAB = 2;

  /**
   * The feature id for the '<em><b>Towofia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__TOWOFIA = 3;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.QareeImpl <em>Qaree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.QareeImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getQaree()
   * @generated
   */
  int QAREE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QAREE__NAME = PERSON__NAME;

  /**
   * The feature id for the '<em><b>Esm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QAREE__ESM = PERSON__ESM;

  /**
   * The feature id for the '<em><b>Lakab</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QAREE__LAKAB = PERSON__LAKAB;

  /**
   * The feature id for the '<em><b>Towofia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QAREE__TOWOFIA = PERSON__TOWOFIA;

  /**
   * The number of structural features of the '<em>Qaree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QAREE_FEATURE_COUNT = PERSON_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.RaweeImpl <em>Rawee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.RaweeImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getRawee()
   * @generated
   */
  int RAWEE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAWEE__NAME = PERSON__NAME;

  /**
   * The feature id for the '<em><b>Esm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAWEE__ESM = PERSON__ESM;

  /**
   * The feature id for the '<em><b>Lakab</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAWEE__LAKAB = PERSON__LAKAB;

  /**
   * The feature id for the '<em><b>Towofia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAWEE__TOWOFIA = PERSON__TOWOFIA;

  /**
   * The feature id for the '<em><b>Qaree</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAWEE__QAREE = PERSON_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rawee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAWEE_FEATURE_COUNT = PERSON_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.qwork.qiraa.impl.TareekImpl <em>Tareek</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.qiraa.impl.TareekImpl
   * @see org.qwork.qiraa.impl.QiraaPackageImpl#getTareek()
   * @generated
   */
  int TAREEK = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAREEK__NAME = 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAREEK__REF = 1;

  /**
   * The number of structural features of the '<em>Tareek</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAREEK_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.QiraaModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.qwork.qiraa.QiraaModel
   * @generated
   */
  EClass getQiraaModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.QiraaModel#getHourouf <em>Hourouf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hourouf</em>'.
   * @see org.qwork.qiraa.QiraaModel#getHourouf()
   * @see #getQiraaModel()
   * @generated
   */
  EReference getQiraaModel_Hourouf();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.QiraaModel#getQoraa <em>Qoraa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Qoraa</em>'.
   * @see org.qwork.qiraa.QiraaModel#getQoraa()
   * @see #getQiraaModel()
   * @generated
   */
  EReference getQiraaModel_Qoraa();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.QiraaModel#getTorok <em>Torok</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Torok</em>'.
   * @see org.qwork.qiraa.QiraaModel#getTorok()
   * @see #getQiraaModel()
   * @generated
   */
  EReference getQiraaModel_Torok();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.QiraaModel#getHarakat <em>Harakat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Harakat</em>'.
   * @see org.qwork.qiraa.QiraaModel#getHarakat()
   * @see #getQiraaModel()
   * @generated
   */
  EReference getQiraaModel_Harakat();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.qiraa.QiraaModel#getRowat <em>Rowat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rowat</em>'.
   * @see org.qwork.qiraa.QiraaModel#getRowat()
   * @see #getQiraaModel()
   * @generated
   */
  EReference getQiraaModel_Rowat();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Harf <em>Harf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Harf</em>'.
   * @see org.qwork.qiraa.Harf
   * @generated
   */
  EClass getHarf();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Harf#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.qwork.qiraa.Harf#getName()
   * @see #getHarf()
   * @generated
   */
  EAttribute getHarf_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.qwork.qiraa.Harf#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see org.qwork.qiraa.Harf#getValues()
   * @see #getHarf()
   * @generated
   */
  EAttribute getHarf_Values();

  /**
   * Returns the meta object for the reference '{@link org.qwork.qiraa.Harf#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.qwork.qiraa.Harf#getRef()
   * @see #getHarf()
   * @generated
   */
  EReference getHarf_Ref();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Harakah <em>Harakah</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Harakah</em>'.
   * @see org.qwork.qiraa.Harakah
   * @generated
   */
  EClass getHarakah();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Harakah#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.qwork.qiraa.Harakah#getName()
   * @see #getHarakah()
   * @generated
   */
  EAttribute getHarakah_Name();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Harakah#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.qwork.qiraa.Harakah#getValue()
   * @see #getHarakah()
   * @generated
   */
  EAttribute getHarakah_Value();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Qaree <em>Qaree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Qaree</em>'.
   * @see org.qwork.qiraa.Qaree
   * @generated
   */
  EClass getQaree();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Rawee <em>Rawee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rawee</em>'.
   * @see org.qwork.qiraa.Rawee
   * @generated
   */
  EClass getRawee();

  /**
   * Returns the meta object for the reference '{@link org.qwork.qiraa.Rawee#getQaree <em>Qaree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Qaree</em>'.
   * @see org.qwork.qiraa.Rawee#getQaree()
   * @see #getRawee()
   * @generated
   */
  EReference getRawee_Qaree();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see org.qwork.qiraa.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.qwork.qiraa.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Person#getEsm <em>Esm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Esm</em>'.
   * @see org.qwork.qiraa.Person#getEsm()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Esm();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Person#getLakab <em>Lakab</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lakab</em>'.
   * @see org.qwork.qiraa.Person#getLakab()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Lakab();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Person#getTowofia <em>Towofia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Towofia</em>'.
   * @see org.qwork.qiraa.Person#getTowofia()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Towofia();

  /**
   * Returns the meta object for class '{@link org.qwork.qiraa.Tareek <em>Tareek</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tareek</em>'.
   * @see org.qwork.qiraa.Tareek
   * @generated
   */
  EClass getTareek();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.qiraa.Tareek#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.qwork.qiraa.Tareek#getName()
   * @see #getTareek()
   * @generated
   */
  EAttribute getTareek_Name();

  /**
   * Returns the meta object for the reference '{@link org.qwork.qiraa.Tareek#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.qwork.qiraa.Tareek#getRef()
   * @see #getTareek()
   * @generated
   */
  EReference getTareek_Ref();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QiraaFactory getQiraaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.QiraaModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.QiraaModelImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getQiraaModel()
     * @generated
     */
    EClass QIRAA_MODEL = eINSTANCE.getQiraaModel();

    /**
     * The meta object literal for the '<em><b>Hourouf</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QIRAA_MODEL__HOUROUF = eINSTANCE.getQiraaModel_Hourouf();

    /**
     * The meta object literal for the '<em><b>Qoraa</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QIRAA_MODEL__QORAA = eINSTANCE.getQiraaModel_Qoraa();

    /**
     * The meta object literal for the '<em><b>Torok</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QIRAA_MODEL__TOROK = eINSTANCE.getQiraaModel_Torok();

    /**
     * The meta object literal for the '<em><b>Harakat</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QIRAA_MODEL__HARAKAT = eINSTANCE.getQiraaModel_Harakat();

    /**
     * The meta object literal for the '<em><b>Rowat</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QIRAA_MODEL__ROWAT = eINSTANCE.getQiraaModel_Rowat();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.HarfImpl <em>Harf</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.HarfImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getHarf()
     * @generated
     */
    EClass HARF = eINSTANCE.getHarf();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HARF__NAME = eINSTANCE.getHarf_Name();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HARF__VALUES = eINSTANCE.getHarf_Values();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HARF__REF = eINSTANCE.getHarf_Ref();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.HarakahImpl <em>Harakah</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.HarakahImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getHarakah()
     * @generated
     */
    EClass HARAKAH = eINSTANCE.getHarakah();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HARAKAH__NAME = eINSTANCE.getHarakah_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HARAKAH__VALUE = eINSTANCE.getHarakah_Value();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.QareeImpl <em>Qaree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.QareeImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getQaree()
     * @generated
     */
    EClass QAREE = eINSTANCE.getQaree();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.RaweeImpl <em>Rawee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.RaweeImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getRawee()
     * @generated
     */
    EClass RAWEE = eINSTANCE.getRawee();

    /**
     * The meta object literal for the '<em><b>Qaree</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RAWEE__QAREE = eINSTANCE.getRawee_Qaree();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.PersonImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '<em><b>Esm</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__ESM = eINSTANCE.getPerson_Esm();

    /**
     * The meta object literal for the '<em><b>Lakab</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__LAKAB = eINSTANCE.getPerson_Lakab();

    /**
     * The meta object literal for the '<em><b>Towofia</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__TOWOFIA = eINSTANCE.getPerson_Towofia();

    /**
     * The meta object literal for the '{@link org.qwork.qiraa.impl.TareekImpl <em>Tareek</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.qiraa.impl.TareekImpl
     * @see org.qwork.qiraa.impl.QiraaPackageImpl#getTareek()
     * @generated
     */
    EClass TAREEK = eINSTANCE.getTareek();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAREEK__NAME = eINSTANCE.getTareek_Name();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAREEK__REF = eINSTANCE.getTareek_Ref();

  }

} //QiraaPackage
