/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ramz</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.qiraa.Ramz#getName <em>Name</em>}</li>
 *   <li>{@link org.qwork.qiraa.Ramz#getRefs <em>Refs</em>}</li>
 * </ul>
 *
 * @see org.qwork.qiraa.QiraaPackage#getRamz()
 * @model
 * @generated
 */
public interface Ramz extends YokraaLahWaRamz
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.qwork.qiraa.QiraaPackage#getRamz_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.qwork.qiraa.Ramz#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Refs</b></em>' reference list.
   * The list contents are of type {@link org.qwork.qiraa.YokraaLah}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refs</em>' reference list.
   * @see org.qwork.qiraa.QiraaPackage#getRamz_Refs()
   * @model
   * @generated
   */
  EList<YokraaLah> getRefs();

} // Ramz
