/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tafsil</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.qiraa.Tafsil#getNass <em>Nass</em>}</li>
 *   <li>{@link org.qwork.qiraa.Tafsil#getKedah <em>Kedah</em>}</li>
 * </ul>
 *
 * @see org.qwork.qiraa.QiraaPackage#getTafsil()
 * @model
 * @generated
 */
public interface Tafsil extends EObject
{
  /**
   * Returns the value of the '<em><b>Nass</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nass</em>' attribute.
   * @see #setNass(String)
   * @see org.qwork.qiraa.QiraaPackage#getTafsil_Nass()
   * @model
   * @generated
   */
  String getNass();

  /**
   * Sets the value of the '{@link org.qwork.qiraa.Tafsil#getNass <em>Nass</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nass</em>' attribute.
   * @see #getNass()
   * @generated
   */
  void setNass(String value);

  /**
   * Returns the value of the '<em><b>Kedah</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.qiraa.Kaaedah}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kedah</em>' containment reference list.
   * @see org.qwork.qiraa.QiraaPackage#getTafsil_Kedah()
   * @model containment="true"
   * @generated
   */
  EList<Kaaedah> getKedah();

} // Tafsil
