/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tareek</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.qiraa.Tareek#getName <em>Name</em>}</li>
 *   <li>{@link org.qwork.qiraa.Tareek#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.qwork.qiraa.QiraaPackage#getTareek()
 * @model
 * @generated
 */
public interface Tareek extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.qwork.qiraa.QiraaPackage#getTareek_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.qwork.qiraa.Tareek#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Tareek)
   * @see org.qwork.qiraa.QiraaPackage#getTareek_Ref()
   * @model
   * @generated
   */
  Tareek getRef();

  /**
   * Sets the value of the '{@link org.qwork.qiraa.Tareek#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Tareek value);

} // Tareek
