/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Yokraa Lah Wa Ramz</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.qwork.qiraa.QiraaPackage#getYokraaLahWaRamz()
 * @model
 * @generated
 */
public interface YokraaLahWaRamz extends EObject
{
} // YokraaLahWaRamz
