/**
 * generated by Xtext 2.25.0
 */
package org.qwork.arabic;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.qwork.arabic.ArabicFactory
 * @model kind="package"
 * @generated
 */
public interface ArabicPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "arabic";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.qwork.org/Arabic";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "arabic";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ArabicPackage eINSTANCE = org.qwork.arabic.impl.ArabicPackageImpl.init();

  /**
   * The meta object id for the '{@link org.qwork.arabic.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.arabic.impl.ModelImpl
   * @see org.qwork.arabic.impl.ArabicPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Phrases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PHRASES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.qwork.arabic.impl.PhraseImpl <em>Phrase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.qwork.arabic.impl.PhraseImpl
   * @see org.qwork.arabic.impl.ArabicPackageImpl#getPhrase()
   * @generated
   */
  int PHRASE = 1;

  /**
   * The feature id for the '<em><b>Basmalah</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHRASE__BASMALAH = 0;

  /**
   * The feature id for the '<em><b>Words</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHRASE__WORDS = 1;

  /**
   * The number of structural features of the '<em>Phrase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHRASE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.qwork.arabic.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.qwork.arabic.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.qwork.arabic.Model#getPhrases <em>Phrases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Phrases</em>'.
   * @see org.qwork.arabic.Model#getPhrases()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Phrases();

  /**
   * Returns the meta object for class '{@link org.qwork.arabic.Phrase <em>Phrase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Phrase</em>'.
   * @see org.qwork.arabic.Phrase
   * @generated
   */
  EClass getPhrase();

  /**
   * Returns the meta object for the attribute '{@link org.qwork.arabic.Phrase#isBasmalah <em>Basmalah</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Basmalah</em>'.
   * @see org.qwork.arabic.Phrase#isBasmalah()
   * @see #getPhrase()
   * @generated
   */
  EAttribute getPhrase_Basmalah();

  /**
   * Returns the meta object for the attribute list '{@link org.qwork.arabic.Phrase#getWords <em>Words</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Words</em>'.
   * @see org.qwork.arabic.Phrase#getWords()
   * @see #getPhrase()
   * @generated
   */
  EAttribute getPhrase_Words();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ArabicFactory getArabicFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.qwork.arabic.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.arabic.impl.ModelImpl
     * @see org.qwork.arabic.impl.ArabicPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Phrases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PHRASES = eINSTANCE.getModel_Phrases();

    /**
     * The meta object literal for the '{@link org.qwork.arabic.impl.PhraseImpl <em>Phrase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.qwork.arabic.impl.PhraseImpl
     * @see org.qwork.arabic.impl.ArabicPackageImpl#getPhrase()
     * @generated
     */
    EClass PHRASE = eINSTANCE.getPhrase();

    /**
     * The meta object literal for the '<em><b>Basmalah</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PHRASE__BASMALAH = eINSTANCE.getPhrase_Basmalah();

    /**
     * The meta object literal for the '<em><b>Words</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PHRASE__WORDS = eINSTANCE.getPhrase_Words();

  }

} //ArabicPackage
