/**
 * generated by Xtext 2.25.0
 */
package org.qwork.arabic;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.arabic.Model#getPhrases <em>Phrases</em>}</li>
 * </ul>
 *
 * @see org.qwork.arabic.ArabicPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Phrases</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.arabic.Phrase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phrases</em>' containment reference list.
   * @see org.qwork.arabic.ArabicPackage#getModel_Phrases()
   * @model containment="true"
   * @generated
   */
  EList<Phrase> getPhrases();

} // Model
