/*
 * generated by Xtext 2.25.0
 */
package org.qwork.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ArabicUiModule extends AbstractArabicUiModule {

	public ArabicUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
