/**
 * generated by Xtext 2.25.0
 */
package org.qwork.osolqiraa.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.qwork.osolqiraa.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.qwork.osolqiraa.OsolqiraaPackage
 * @generated
 */
public class OsolqiraaSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static OsolqiraaPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OsolqiraaSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = OsolqiraaPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case OsolqiraaPackage.OSOL_QIRAA_MODEL:
      {
        OsolQiraaModel osolQiraaModel = (OsolQiraaModel)theEObject;
        T result = caseOsolQiraaModel(osolQiraaModel);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.PERSON:
      {
        Person person = (Person)theEObject;
        T result = casePerson(person);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.DOUAA:
      {
        Douaa douaa = (Douaa)theEObject;
        T result = caseDouaa(douaa);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.IMAM:
      {
        IMAM imam = (IMAM)theEObject;
        T result = caseIMAM(imam);
        if (result == null) result = casePerson(imam);
        if (result == null) result = caseDouaa(imam);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.QAREE:
      {
        Qaree qaree = (Qaree)theEObject;
        T result = caseQaree(qaree);
        if (result == null) result = casePerson(qaree);
        if (result == null) result = caseYokraaLah(qaree);
        if (result == null) result = caseYokraaLahWaRamz(qaree);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.RAWEE:
      {
        Rawee rawee = (Rawee)theEObject;
        T result = caseRawee(rawee);
        if (result == null) result = casePerson(rawee);
        if (result == null) result = caseYokraaLah(rawee);
        if (result == null) result = caseYokraaLahWaRamz(rawee);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.YOKRAA_LAH:
      {
        YokraaLah yokraaLah = (YokraaLah)theEObject;
        T result = caseYokraaLah(yokraaLah);
        if (result == null) result = caseYokraaLahWaRamz(yokraaLah);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.TAREEK:
      {
        Tareek tareek = (Tareek)theEObject;
        T result = caseTareek(tareek);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.KAYD:
      {
        Kayd kayd = (Kayd)theEObject;
        T result = caseKayd(kayd);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.ISTELAH:
      {
        Istelah istelah = (Istelah)theEObject;
        T result = caseIstelah(istelah);
        if (result == null) result = caseYokraaLah(istelah);
        if (result == null) result = caseYokraaLahWaRamz(istelah);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.RAMZ:
      {
        Ramz ramz = (Ramz)theEObject;
        T result = caseRamz(ramz);
        if (result == null) result = caseYokraaLahWaRamz(ramz);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.YOKRAA_LAH_WA_RAMZ:
      {
        YokraaLahWaRamz yokraaLahWaRamz = (YokraaLahWaRamz)theEObject;
        T result = caseYokraaLahWaRamz(yokraaLahWaRamz);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OsolqiraaPackage.HARF_QURAN:
      {
        HarfQuran harfQuran = (HarfQuran)theEObject;
        T result = caseHarfQuran(harfQuran);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Osol Qiraa Model</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Osol Qiraa Model</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOsolQiraaModel(OsolQiraaModel object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePerson(Person object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Douaa</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Douaa</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDouaa(Douaa object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>IMAM</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>IMAM</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIMAM(IMAM object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Qaree</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Qaree</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseQaree(Qaree object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Rawee</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Rawee</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRawee(Rawee object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Yokraa Lah</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Yokraa Lah</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseYokraaLah(YokraaLah object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Tareek</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Tareek</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTareek(Tareek object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Kayd</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Kayd</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseKayd(Kayd object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Istelah</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Istelah</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIstelah(Istelah object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ramz</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ramz</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRamz(Ramz object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Yokraa Lah Wa Ramz</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Yokraa Lah Wa Ramz</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseYokraaLahWaRamz(YokraaLahWaRamz object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Harf Quran</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Harf Quran</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseHarfQuran(HarfQuran object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //OsolqiraaSwitch
