/**
 * generated by Xtext 2.25.0
 */
package org.qwork.matn.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.qwork.matn.Bayt;
import org.qwork.matn.Maktah;
import org.qwork.matn.MatnPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Maktah</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.matn.impl.MaktahImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.qwork.matn.impl.MaktahImpl#getAbyatCount <em>Abyat Count</em>}</li>
 *   <li>{@link org.qwork.matn.impl.MaktahImpl#getAbyat <em>Abyat</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MaktahImpl extends MinimalEObjectImpl.Container implements Maktah
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getAbyatCount() <em>Abyat Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbyatCount()
   * @generated
   * @ordered
   */
  protected static final int ABYAT_COUNT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getAbyatCount() <em>Abyat Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbyatCount()
   * @generated
   * @ordered
   */
  protected int abyatCount = ABYAT_COUNT_EDEFAULT;

  /**
   * The cached value of the '{@link #getAbyat() <em>Abyat</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbyat()
   * @generated
   * @ordered
   */
  protected EList<Bayt> abyat;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MaktahImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MatnPackage.Literals.MAKTAH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MatnPackage.MAKTAH__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getAbyatCount()
  {
    return abyatCount;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAbyatCount(int newAbyatCount)
  {
    int oldAbyatCount = abyatCount;
    abyatCount = newAbyatCount;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MatnPackage.MAKTAH__ABYAT_COUNT, oldAbyatCount, abyatCount));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Bayt> getAbyat()
  {
    if (abyat == null)
    {
      abyat = new EObjectContainmentEList<Bayt>(Bayt.class, this, MatnPackage.MAKTAH__ABYAT);
    }
    return abyat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MatnPackage.MAKTAH__ABYAT:
        return ((InternalEList<?>)getAbyat()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MatnPackage.MAKTAH__NAME:
        return getName();
      case MatnPackage.MAKTAH__ABYAT_COUNT:
        return getAbyatCount();
      case MatnPackage.MAKTAH__ABYAT:
        return getAbyat();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MatnPackage.MAKTAH__NAME:
        setName((String)newValue);
        return;
      case MatnPackage.MAKTAH__ABYAT_COUNT:
        setAbyatCount((Integer)newValue);
        return;
      case MatnPackage.MAKTAH__ABYAT:
        getAbyat().clear();
        getAbyat().addAll((Collection<? extends Bayt>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MatnPackage.MAKTAH__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MatnPackage.MAKTAH__ABYAT_COUNT:
        setAbyatCount(ABYAT_COUNT_EDEFAULT);
        return;
      case MatnPackage.MAKTAH__ABYAT:
        getAbyat().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MatnPackage.MAKTAH__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MatnPackage.MAKTAH__ABYAT_COUNT:
        return abyatCount != ABYAT_COUNT_EDEFAULT;
      case MatnPackage.MAKTAH__ABYAT:
        return abyat != null && !abyat.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", abyatCount: ");
    result.append(abyatCount);
    result.append(')');
    return result.toString();
  }

} //MaktahImpl
