/*
 * generated by Xtext 2.25.0
 */
package org.qwork.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.qwork.parser.antlr.internal.InternalMatnParser;
import org.qwork.services.MatnGrammarAccess;

public class MatnParser extends AbstractAntlrParser {

	@Inject
	private MatnGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMatnParser createParser(XtextTokenStream stream) {
		return new InternalMatnParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MatnModel";
	}

	public MatnGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MatnGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
