/*
 * generated by Xtext 2.25.0
 */
package org.qwork.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.qwork.parser.antlr.internal.InternalQAyahStartParser;
import org.qwork.services.QAyahStartGrammarAccess;

public class QAyahStartParser extends AbstractAntlrParser {

	@Inject
	private QAyahStartGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQAyahStartParser createParser(XtextTokenStream stream) {
		return new InternalQAyahStartParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AyahStartModel";
	}

	public QAyahStartGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QAyahStartGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
