/*
 * generated by Xtext 2.25.0
 */
package org.qwork.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.qwork.OsolQiraaRuntimeModule;
import org.qwork.OsolQiraaStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OsolQiraaIdeSetup extends OsolQiraaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OsolQiraaRuntimeModule(), new OsolQiraaIdeModule()));
	}
	
}
