/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qayahstart;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ayah Start Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.qayahstart.AyahStartModel#getAyat <em>Ayat</em>}</li>
 * </ul>
 *
 * @see org.qwork.qayahstart.QayahstartPackage#getAyahStartModel()
 * @model
 * @generated
 */
public interface AyahStartModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Ayat</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.qayahstart.AyahStart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ayat</em>' containment reference list.
   * @see org.qwork.qayahstart.QayahstartPackage#getAyahStartModel_Ayat()
   * @model containment="true"
   * @generated
   */
  EList<AyahStart> getAyat();

} // AyahStartModel
