/**
 * generated by Xtext 2.25.0
 */
package org.qwork.matn;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Maktah</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.matn.Maktah#getName <em>Name</em>}</li>
 *   <li>{@link org.qwork.matn.Maktah#getAbyatCount <em>Abyat Count</em>}</li>
 *   <li>{@link org.qwork.matn.Maktah#getAbyat <em>Abyat</em>}</li>
 * </ul>
 *
 * @see org.qwork.matn.MatnPackage#getMaktah()
 * @model
 * @generated
 */
public interface Maktah extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.qwork.matn.MatnPackage#getMaktah_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.qwork.matn.Maktah#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Abyat Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abyat Count</em>' attribute.
   * @see #setAbyatCount(int)
   * @see org.qwork.matn.MatnPackage#getMaktah_AbyatCount()
   * @model
   * @generated
   */
  int getAbyatCount();

  /**
   * Sets the value of the '{@link org.qwork.matn.Maktah#getAbyatCount <em>Abyat Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abyat Count</em>' attribute.
   * @see #getAbyatCount()
   * @generated
   */
  void setAbyatCount(int value);

  /**
   * Returns the value of the '<em><b>Abyat</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.matn.Bayt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abyat</em>' containment reference list.
   * @see org.qwork.matn.MatnPackage#getMaktah_Abyat()
   * @model containment="true"
   * @generated
   */
  EList<Bayt> getAbyat();

} // Maktah
