/**
 * generated by Xtext 2.25.0
 */
package org.qwork.matn;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.matn.MatnModel#getMatn <em>Matn</em>}</li>
 * </ul>
 *
 * @see org.qwork.matn.MatnPackage#getMatnModel()
 * @model
 * @generated
 */
public interface MatnModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Matn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Matn</em>' containment reference.
   * @see #setMatn(Matn)
   * @see org.qwork.matn.MatnPackage#getMatnModel_Matn()
   * @model containment="true"
   * @generated
   */
  Matn getMatn();

  /**
   * Sets the value of the '{@link org.qwork.matn.MatnModel#getMatn <em>Matn</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Matn</em>' containment reference.
   * @see #getMatn()
   * @generated
   */
  void setMatn(Matn value);

} // MatnModel
