/*
 * generated by Xtext 2.24.0
 */
package org.qwork;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ArabicStandaloneSetup extends ArabicStandaloneSetupGenerated {

	public static void doSetup() {
		new ArabicStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
