/*
 * generated by Xtext 2.25.0
 */
package org.qwork;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MatnStandaloneSetup extends MatnStandaloneSetupGenerated {

	public static void doSetup() {
		new MatnStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
