/*
 * generated by Xtext 2.25.0
 */
package org.qwork.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.qwork.AbjadRuntimeModule;
import org.qwork.AbjadStandaloneSetup;
import org.qwork.ide.AbjadIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class AbjadWebSetup extends AbjadStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AbjadRuntimeModule(), new AbjadIdeModule(), new AbjadWebModule()));
	}
	
}
