/*
 * generated by Xtext 2.25.0
 */
package org.qwork.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.qwork.QiraaRuntimeModule;
import org.qwork.QiraaStandaloneSetup;
import org.qwork.ide.QiraaIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class QiraaWebSetup extends QiraaStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QiraaRuntimeModule(), new QiraaIdeModule(), new QiraaWebModule()));
	}
	
}
