/*
 * generated by Xtext 2.25.0
 */
package org.qwork.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link AbjadWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractAbjadWebModule extends DefaultWebModule {

}
