/**
 * generated by Xtext 2.25.0
 */
package org.qwork.osolqiraa;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.qwork.osolqiraa.OsolqiraaPackage
 * @generated
 */
public interface OsolqiraaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OsolqiraaFactory eINSTANCE = org.qwork.osolqiraa.impl.OsolqiraaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Osol Qiraa Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Osol Qiraa Model</em>'.
   * @generated
   */
  OsolQiraaModel createOsolQiraaModel();

  /**
   * Returns a new object of class '<em>Person</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person</em>'.
   * @generated
   */
  Person createPerson();

  /**
   * Returns a new object of class '<em>Douaa</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Douaa</em>'.
   * @generated
   */
  Douaa createDouaa();

  /**
   * Returns a new object of class '<em>IMAM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IMAM</em>'.
   * @generated
   */
  IMAM createIMAM();

  /**
   * Returns a new object of class '<em>Qaree</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Qaree</em>'.
   * @generated
   */
  Qaree createQaree();

  /**
   * Returns a new object of class '<em>Rawee</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rawee</em>'.
   * @generated
   */
  Rawee createRawee();

  /**
   * Returns a new object of class '<em>Yokraa Lah</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Yokraa Lah</em>'.
   * @generated
   */
  YokraaLah createYokraaLah();

  /**
   * Returns a new object of class '<em>Tareek</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tareek</em>'.
   * @generated
   */
  Tareek createTareek();

  /**
   * Returns a new object of class '<em>Kayd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Kayd</em>'.
   * @generated
   */
  Kayd createKayd();

  /**
   * Returns a new object of class '<em>Istelah</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Istelah</em>'.
   * @generated
   */
  Istelah createIstelah();

  /**
   * Returns a new object of class '<em>Ramz</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ramz</em>'.
   * @generated
   */
  Ramz createRamz();

  /**
   * Returns a new object of class '<em>Yokraa Lah Wa Ramz</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Yokraa Lah Wa Ramz</em>'.
   * @generated
   */
  YokraaLahWaRamz createYokraaLahWaRamz();

  /**
   * Returns a new object of class '<em>Harf Quran</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Harf Quran</em>'.
   * @generated
   */
  HarfQuran createHarfQuran();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  OsolqiraaPackage getOsolqiraaPackage();

} //OsolqiraaFactory
