/**
 * generated by Xtext 2.25.0
 */
package org.qwork.osolqiraa;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Osol Qiraa Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.osolqiraa.OsolQiraaModel#getQoraa <em>Qoraa</em>}</li>
 *   <li>{@link org.qwork.osolqiraa.OsolQiraaModel#getTorok <em>Torok</em>}</li>
 *   <li>{@link org.qwork.osolqiraa.OsolQiraaModel#getRowat <em>Rowat</em>}</li>
 *   <li>{@link org.qwork.osolqiraa.OsolQiraaModel#getImams <em>Imams</em>}</li>
 *   <li>{@link org.qwork.osolqiraa.OsolQiraaModel#getIstelahat <em>Istelahat</em>}</li>
 *   <li>{@link org.qwork.osolqiraa.OsolQiraaModel#getKoyod <em>Koyod</em>}</li>
 * </ul>
 *
 * @see org.qwork.osolqiraa.OsolqiraaPackage#getOsolQiraaModel()
 * @model
 * @generated
 */
public interface OsolQiraaModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Qoraa</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.osolqiraa.Qaree}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qoraa</em>' containment reference list.
   * @see org.qwork.osolqiraa.OsolqiraaPackage#getOsolQiraaModel_Qoraa()
   * @model containment="true"
   * @generated
   */
  EList<Qaree> getQoraa();

  /**
   * Returns the value of the '<em><b>Torok</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.osolqiraa.Tareek}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Torok</em>' containment reference list.
   * @see org.qwork.osolqiraa.OsolqiraaPackage#getOsolQiraaModel_Torok()
   * @model containment="true"
   * @generated
   */
  EList<Tareek> getTorok();

  /**
   * Returns the value of the '<em><b>Rowat</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.osolqiraa.Rawee}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rowat</em>' containment reference list.
   * @see org.qwork.osolqiraa.OsolqiraaPackage#getOsolQiraaModel_Rowat()
   * @model containment="true"
   * @generated
   */
  EList<Rawee> getRowat();

  /**
   * Returns the value of the '<em><b>Imams</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.osolqiraa.IMAM}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imams</em>' containment reference list.
   * @see org.qwork.osolqiraa.OsolqiraaPackage#getOsolQiraaModel_Imams()
   * @model containment="true"
   * @generated
   */
  EList<IMAM> getImams();

  /**
   * Returns the value of the '<em><b>Istelahat</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.osolqiraa.Istelah}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Istelahat</em>' containment reference list.
   * @see org.qwork.osolqiraa.OsolqiraaPackage#getOsolQiraaModel_Istelahat()
   * @model containment="true"
   * @generated
   */
  EList<Istelah> getIstelahat();

  /**
   * Returns the value of the '<em><b>Koyod</b></em>' containment reference list.
   * The list contents are of type {@link org.qwork.osolqiraa.Kayd}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Koyod</em>' containment reference list.
   * @see org.qwork.osolqiraa.OsolqiraaPackage#getOsolQiraaModel_Koyod()
   * @model containment="true"
   * @generated
   */
  EList<Kayd> getKoyod();

} // OsolQiraaModel
