/**
 * generated by Xtext 2.25.0
 */
package org.qwork.osolqiraa;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Qaree</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.qwork.osolqiraa.OsolqiraaPackage#getQaree()
 * @model
 * @generated
 */
public interface Qaree extends Person, YokraaLah
{
} // Qaree
