/**
 * generated by Xtext 2.25.0
 */
package org.qwork.abjad;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.qwork.abjad.AbjadPackage
 * @generated
 */
public interface AbjadFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AbjadFactory eINSTANCE = org.qwork.abjad.impl.AbjadFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  AbjadModel createAbjadModel();

  /**
   * Returns a new object of class '<em>Harf</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Harf</em>'.
   * @generated
   */
  Harf createHarf();

  /**
   * Returns a new object of class '<em>Harakah</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Harakah</em>'.
   * @generated
   */
  Harakah createHarakah();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AbjadPackage getAbjadPackage();

} //AbjadFactory
