/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.qwork.qiraa.HarfQuran;
import org.qwork.qiraa.Kaaedah;
import org.qwork.qiraa.Kayd;
import org.qwork.qiraa.QiraaPackage;
import org.qwork.qiraa.YokraaLahWaRamz;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Kaaedah</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.qiraa.impl.KaaedahImpl#getRefs <em>Refs</em>}</li>
 *   <li>{@link org.qwork.qiraa.impl.KaaedahImpl#getKayd <em>Kayd</em>}</li>
 *   <li>{@link org.qwork.qiraa.impl.KaaedahImpl#getHarf <em>Harf</em>}</li>
 * </ul>
 *
 * @generated
 */
public class KaaedahImpl extends MinimalEObjectImpl.Container implements Kaaedah
{
  /**
   * The cached value of the '{@link #getRefs() <em>Refs</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefs()
   * @generated
   * @ordered
   */
  protected EList<YokraaLahWaRamz> refs;

  /**
   * The cached value of the '{@link #getKayd() <em>Kayd</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKayd()
   * @generated
   * @ordered
   */
  protected Kayd kayd;

  /**
   * The cached value of the '{@link #getHarf() <em>Harf</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHarf()
   * @generated
   * @ordered
   */
  protected HarfQuran harf;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected KaaedahImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QiraaPackage.Literals.KAAEDAH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<YokraaLahWaRamz> getRefs()
  {
    if (refs == null)
    {
      refs = new EObjectResolvingEList<YokraaLahWaRamz>(YokraaLahWaRamz.class, this, QiraaPackage.KAAEDAH__REFS);
    }
    return refs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Kayd getKayd()
  {
    if (kayd != null && kayd.eIsProxy())
    {
      InternalEObject oldKayd = (InternalEObject)kayd;
      kayd = (Kayd)eResolveProxy(oldKayd);
      if (kayd != oldKayd)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, QiraaPackage.KAAEDAH__KAYD, oldKayd, kayd));
      }
    }
    return kayd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Kayd basicGetKayd()
  {
    return kayd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKayd(Kayd newKayd)
  {
    Kayd oldKayd = kayd;
    kayd = newKayd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QiraaPackage.KAAEDAH__KAYD, oldKayd, kayd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HarfQuran getHarf()
  {
    return harf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetHarf(HarfQuran newHarf, NotificationChain msgs)
  {
    HarfQuran oldHarf = harf;
    harf = newHarf;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QiraaPackage.KAAEDAH__HARF, oldHarf, newHarf);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHarf(HarfQuran newHarf)
  {
    if (newHarf != harf)
    {
      NotificationChain msgs = null;
      if (harf != null)
        msgs = ((InternalEObject)harf).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QiraaPackage.KAAEDAH__HARF, null, msgs);
      if (newHarf != null)
        msgs = ((InternalEObject)newHarf).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QiraaPackage.KAAEDAH__HARF, null, msgs);
      msgs = basicSetHarf(newHarf, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QiraaPackage.KAAEDAH__HARF, newHarf, newHarf));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QiraaPackage.KAAEDAH__HARF:
        return basicSetHarf(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QiraaPackage.KAAEDAH__REFS:
        return getRefs();
      case QiraaPackage.KAAEDAH__KAYD:
        if (resolve) return getKayd();
        return basicGetKayd();
      case QiraaPackage.KAAEDAH__HARF:
        return getHarf();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QiraaPackage.KAAEDAH__REFS:
        getRefs().clear();
        getRefs().addAll((Collection<? extends YokraaLahWaRamz>)newValue);
        return;
      case QiraaPackage.KAAEDAH__KAYD:
        setKayd((Kayd)newValue);
        return;
      case QiraaPackage.KAAEDAH__HARF:
        setHarf((HarfQuran)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QiraaPackage.KAAEDAH__REFS:
        getRefs().clear();
        return;
      case QiraaPackage.KAAEDAH__KAYD:
        setKayd((Kayd)null);
        return;
      case QiraaPackage.KAAEDAH__HARF:
        setHarf((HarfQuran)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QiraaPackage.KAAEDAH__REFS:
        return refs != null && !refs.isEmpty();
      case QiraaPackage.KAAEDAH__KAYD:
        return kayd != null;
      case QiraaPackage.KAAEDAH__HARF:
        return harf != null;
    }
    return super.eIsSet(featureID);
  }

} //KaaedahImpl
