/**
 * generated by Xtext 2.25.0
 */
package org.qwork.qiraa.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.qwork.qiraa.IMAM;
import org.qwork.qiraa.Maktah;
import org.qwork.qiraa.Marjeh;
import org.qwork.qiraa.QiraaPackage;
import org.qwork.qiraa.Ramz;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Marjeh</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.qwork.qiraa.impl.MarjehImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.qwork.qiraa.impl.MarjehImpl#getRef <em>Ref</em>}</li>
 *   <li>{@link org.qwork.qiraa.impl.MarjehImpl#getRomoz <em>Romoz</em>}</li>
 *   <li>{@link org.qwork.qiraa.impl.MarjehImpl#getMakateh <em>Makateh</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MarjehImpl extends DouaaImpl implements Marjeh
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getRef() <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRef()
   * @generated
   * @ordered
   */
  protected IMAM ref;

  /**
   * The cached value of the '{@link #getRomoz() <em>Romoz</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRomoz()
   * @generated
   * @ordered
   */
  protected EList<Ramz> romoz;

  /**
   * The cached value of the '{@link #getMakateh() <em>Makateh</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMakateh()
   * @generated
   * @ordered
   */
  protected EList<Maktah> makateh;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MarjehImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QiraaPackage.Literals.MARJEH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QiraaPackage.MARJEH__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IMAM getRef()
  {
    if (ref != null && ref.eIsProxy())
    {
      InternalEObject oldRef = (InternalEObject)ref;
      ref = (IMAM)eResolveProxy(oldRef);
      if (ref != oldRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, QiraaPackage.MARJEH__REF, oldRef, ref));
      }
    }
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IMAM basicGetRef()
  {
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRef(IMAM newRef)
  {
    IMAM oldRef = ref;
    ref = newRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QiraaPackage.MARJEH__REF, oldRef, ref));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Ramz> getRomoz()
  {
    if (romoz == null)
    {
      romoz = new EObjectContainmentEList<Ramz>(Ramz.class, this, QiraaPackage.MARJEH__ROMOZ);
    }
    return romoz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Maktah> getMakateh()
  {
    if (makateh == null)
    {
      makateh = new EObjectContainmentEList<Maktah>(Maktah.class, this, QiraaPackage.MARJEH__MAKATEH);
    }
    return makateh;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QiraaPackage.MARJEH__ROMOZ:
        return ((InternalEList<?>)getRomoz()).basicRemove(otherEnd, msgs);
      case QiraaPackage.MARJEH__MAKATEH:
        return ((InternalEList<?>)getMakateh()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QiraaPackage.MARJEH__NAME:
        return getName();
      case QiraaPackage.MARJEH__REF:
        if (resolve) return getRef();
        return basicGetRef();
      case QiraaPackage.MARJEH__ROMOZ:
        return getRomoz();
      case QiraaPackage.MARJEH__MAKATEH:
        return getMakateh();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QiraaPackage.MARJEH__NAME:
        setName((String)newValue);
        return;
      case QiraaPackage.MARJEH__REF:
        setRef((IMAM)newValue);
        return;
      case QiraaPackage.MARJEH__ROMOZ:
        getRomoz().clear();
        getRomoz().addAll((Collection<? extends Ramz>)newValue);
        return;
      case QiraaPackage.MARJEH__MAKATEH:
        getMakateh().clear();
        getMakateh().addAll((Collection<? extends Maktah>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QiraaPackage.MARJEH__NAME:
        setName(NAME_EDEFAULT);
        return;
      case QiraaPackage.MARJEH__REF:
        setRef((IMAM)null);
        return;
      case QiraaPackage.MARJEH__ROMOZ:
        getRomoz().clear();
        return;
      case QiraaPackage.MARJEH__MAKATEH:
        getMakateh().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QiraaPackage.MARJEH__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case QiraaPackage.MARJEH__REF:
        return ref != null;
      case QiraaPackage.MARJEH__ROMOZ:
        return romoz != null && !romoz.isEmpty();
      case QiraaPackage.MARJEH__MAKATEH:
        return makateh != null && !makateh.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //MarjehImpl
